"""Builds data/stages/*.json for the remade Act One (level paintings + pixel detection).
The JSON files are the source of truth in the project; this is just a convenient way to write them."""
import json, os, sys, importlib
sys.path.insert(0, os.path.dirname(__file__))
import sense_params
importlib.reload(sense_params)
P = sense_params.SENSE
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'data', 'stages')

HINT_CONTROLS = ("Walk: WASD / arrows, or click the ground     Talk: Z / Enter, or click someone     "
                 "Menu: X / Esc, or right-click")


def base(id_, art_key, **kw):
    p = P[art_key]
    st = {"id": id_, "level": {"art": p.get("art", art_key), "scale": p["scale"]},
          "sense": p["sense"], "start": p["start"], "exit": p.get("exit", {"edge": "right"})}
    st.update(kw)
    return st


STAGES = []

# ============================================================== I. Harrowgate (ages 5, 7, 9)
s = base("s01_harrowgate", "village_road",
         name="Harrowgate", chapter="I.   Harrowgate", age="five, seven, nine",
         tint="#f4efe2", weather="", start_facing="right",
         derrick={"form": "tot", "level": 1},
         depth=[{"art": "fore/village_fore", "scale": 0.8, "speed": 1.3}],
         mist=[{"y": 10, "h": 200, "speed": 0.55, "alpha": 0.18}],
         gates={"spring": {"rect": [21, 0, 1, 13]}, "summer": {"rect": [44, 0, 1, 13]}},
         lines={"a": {"x": 3}, "b": {"x": 8}, "c": {"x": 11}, "d": {"x": 19},
                "e": {"x": 24}, "f": {"x": 29}, "g": {"x": 34}, "h": {"x": 38}, "i": {"x": 43},
                "j": {"x": 47}, "k": {"x": 51}, "l": {"x": 60}},
         triggers={"a": "spring_walk", "b": "spring_patch", "c": "spring_father", "d": "skip_one",
                   "e": "summer_kids", "f": "summer_well", "g": "summer_talk", "h": "summer_stick", "i": "skip_two",
                   "j": "autumn_hooves", "k": "autumn_green", "l": "autumn_home"},
         cast={
             # spring, age five
             "M": {"id": "mother", "at": [3, 5], "facing": "right"},
             "F": {"id": "father", "at": [12, 8], "facing": "left"},
             "P": {"id": "patch", "at": [14, 6], "hidden": True, "facing": "left", "solid": False},
             # summer, age seven
             "E": {"id": "kid_a", "at": [26, 5], "facing": "right", "hidden": True},
             "K": {"id": "kid_b", "at": [28, 5], "facing": "left", "hidden": True},
             "N": {"id": "mother7", "cast": "mother", "at": [30, 5], "facing": "right", "hidden": True},
             "V": {"id": "villager1", "cast": "villager", "at": [36, 8], "facing": "right", "hidden": True},
             "W": {"id": "villager2", "cast": "villager_f", "at": [37, 8], "facing": "left", "hidden": True},
             "H": {"id": "father7", "cast": "father", "at": [40, 5], "facing": "left", "hidden": True},
             # autumn, age nine
             "A": {"id": "kid_a9", "cast": "kid_a", "at": [49, 5], "facing": "right", "hidden": True},
             "B": {"id": "kid_b9", "cast": "kid_b", "at": [50, 8], "facing": "right", "hidden": True},
             "G": {"id": "gauntley", "at": [55, 5], "facing": "left", "hidden": True},
             "O": {"id": "horse", "at": [57, 5], "facing": "left", "hidden": True},
             "R": {"id": "gauntley_rider", "at": [57, 6], "hidden": True},
             "X": {"id": "villager3", "cast": "villager", "at": [53, 8], "facing": "right", "hidden": True},
             "Y": {"id": "villager4", "cast": "villager_f", "at": [59, 8], "facing": "left", "hidden": True},
             "Q": {"id": "mother9", "cast": "mother", "at": [64, 6], "facing": "left", "hidden": True},
             "Z": {"id": "father9", "cast": "father", "at": [65, 7], "facing": "left", "hidden": True},
         },
         on_enter="spring_intro", on_exit="autumn_outro")
s["scripts"] = {
    "spring_intro": [
        {"card": "Harrowgate", "sub": "The spring Derrick was five.", "hold": 2.4},
        {"sound": "Larks. A plough horse blowing, somewhere past the hedges."},
        {"caption": "Harrowgate was the whole world, then. It had a church with one bell, a green, and a well deeper than God."},
        {"camera": [16, 5], "time": 2.0},
        {"wait": 0.4},
        {"camera": "player", "time": 1.0},
        {"hint": HINT_CONTROLS},
    ],
    "spring_walk": [
        {"face": "mother", "to": "player"},
        {"talk": [["mother", "Stay on the road, Derrick. The furrows are your father's, not yours."],
                  ["derrick", "I know."], ["mother", "You know. And yesterday?"],
                  ["derrick", "...Yesterday I didn't know."]]},
        {"act": "mother", "do": "nod"},
        {"walk": "mother", "to": [10, 5], "speed": 2.5, "wait": False},
    ],
    "spring_patch": [
        {"sound": "A dog, barking for joy at nothing in particular."},
        {"show": "patch", "wait": False},
        {"walk": "patch", "path": [[10, 6], [10, 7], [7, 7]], "speed": 7},
        {"face": "patch", "to": "player"},
        {"emote": "player", "text": "!"},
        {"caption": "Patch belonged to everyone and to no one. He liked Derrick best, because Derrick was nearest the ground."},
        {"walk": "patch", "path": [[11, 7], [13, 7]], "speed": 7, "wait": False},
    ],
    "spring_father": [
        {"face": "father", "to": "player"},
        {"talk": [["father", "Here he is. Come to take the plough off me?"],
                  ["derrick", "I can do it."],
                  ["father", "Course you can. Hands here. Lean on it. Now push."]]},
        {"act": "player", "do": "attack", "wait": True},
        {"caption": "The plough did not move. His father pushed it for him, and told everyone at supper that Derrick had ploughed a furrow."},
        {"walk": "mother", "to": [11, 6], "speed": 3},
        {"talk": [["mother", "He'll be wanting wages next."],
                  ["father", "He'll be wanting a sword next. Look at him."]]},
    ],
    "skip_one": [
        {"sound": "The church bell. One stroke, for noon."},
        {"caption": "The furrows came up green. Then gold. Then bare. Then green again."},
        {"fade": "out", "time": 1.2},
        {"gate": "spring", "on": True},
        {"hide": "mother", "wait": False}, {"hide": "father", "wait": False}, {"hide": "patch", "wait": False},
        {"teleport": "player", "to": [23, 6]},
        {"face": "player", "dir": "right"},
        {"tint": "#fff2d4", "time": 0.1},
        {"card": "Two summers later.", "sub": "", "hold": 1.8},
        {"age": "small", "level": 1, "text": "Derrick, seven."},
        {"show": "kid_a", "wait": False}, {"show": "kid_b", "wait": False}, {"show": "mother7", "wait": False},
        {"show": "villager1", "wait": False}, {"show": "villager2", "wait": False}, {"show": "father7", "wait": False},
        {"camera": "player", "time": 0.0},
        {"fade": "in", "time": 1.2},
        {"sound": "Summer. Somebody's washing, slapping on a stone. Children shrieking."},
    ],
    "summer_kids": [
        {"act": "kid_b", "do": "attack"},
        {"talk": [["kid_b", "Die, foul dragon! Die!"],
                  ["kid_a", "I'm not the dragon! I was the dragon yesterday!"],
                  ["kid_b", "Derrick can be the dragon."],
                  ["kid_a", "Derrick's always the dragon."]]},
        {"face": "kid_a", "to": "player"}, {"face": "kid_b", "to": "player"},
        {"act": "player", "do": "raise", "wait": True},
        {"emote": "player", "text": "RAAH"},
        {"act": "kid_b", "do": "attack", "wait": True},
        {"act": "player", "do": "reset"},
        {"fall": "player"},
        {"caption": "He was a very good dragon. He died beautifully, and often."},
        {"rise": "player"},
    ],
    "summer_well": [
        {"face": "mother7", "to": "player"},
        {"talk": [["mother7", "Derrick. Come here. Let me look at you."],
                  ["mother7", "You've grown a hand since spring. I'll have to let your sleeves out again."],
                  ["derrick", "Tam says I'm the smallest."],
                  ["mother7", "Tam's mother says Tam is the cleverest. We all say things."]]},
    ],
    "summer_talk": [
        {"talk": [["villager1", "They say Ser Gauntley killed a wyrm at Kell Bridge."],
                  ["villager2", "There's no such thing as wyrms."],
                  ["villager1", "Not any more there isn't."]]},
        {"caption": "He had seen a knight once, painted on the chapel wall, killing something with too many teeth. He had looked at it every Sunday since."},
    ],
    "summer_stick": [
        {"face": "father7", "to": "player"},
        {"talk": [["father7", "Here. Ash. It'll not break on the first dragon."],
                  ["derrick", "It's a sword."],
                  ["father7", "It's a stick. Swords are for men who can't win an argument."],
                  ["mother7", "Hob."],
                  ["father7", "...It's a sword."]]},
        {"caption": "He slept with it. He was not supposed to sleep with it."},
    ],
    "skip_two": [
        {"caption": "He was the dragon for two more summers. He got very good at dying."},
        {"fade": "out", "time": 1.2},
        {"gate": "summer", "on": True},
        {"hide": "kid_a", "wait": False}, {"hide": "kid_b", "wait": False}, {"hide": "mother7", "wait": False},
        {"hide": "villager1", "wait": False}, {"hide": "villager2", "wait": False}, {"hide": "father7", "wait": False},
        {"teleport": "player", "to": [46, 6]},
        {"face": "player", "dir": "right"},
        {"tint": "#ffe3bd", "time": 0.1},
        {"card": "The autumn he was nine.", "sub": "", "hold": 1.8},
        {"age": "child", "level": 1, "text": "Derrick, nine."},
        {"show": "kid_a9", "wait": False}, {"show": "kid_b9", "wait": False},
        {"show": "gauntley", "wait": False}, {"show": "horse", "wait": False},
        {"show": "villager3", "wait": False}, {"show": "villager4", "wait": False},
        {"show": "mother9", "wait": False}, {"show": "father9", "wait": False},
        {"camera": "player", "time": 0.0},
        {"fade": "in", "time": 1.2},
    ],
    "autumn_hooves": [
        {"sound": "Hooves on the green. A big horse, snorting."},
        {"emote": "kid_a9", "text": "!"}, {"emote": "kid_b9", "text": "!"},
        {"talk": [["kid_a9", "Listen! That's him. It's really him!"],
                  ["kid_b9", "The knight! Ser Gauntley's on the green!"]]},
        {"walk": "kid_a9", "path": [[52, 5]], "speed": 6, "wait": False},
        {"walk": "kid_b9", "path": [[54, 8]], "speed": 6},
        {"caption": "The knight from the chapel wall. The real one. On their green."},
    ],
    "autumn_green": [
        {"camera": "gauntley", "time": 1.4, "wait": False},
        {"zoom": 1.25, "time": 1.4, "wait": True},
        {"act": "gauntley", "do": "raise"},
        {"talk": [["gauntley", "...and THAT is why you never, ever let a goose see you're frightened. They can smell it. Same as bishops."],
                  ["villager3", "Ha! Go on, Ser!"],
                  ["gauntley", "No, no, that's all the wisdom I've got. The rest is just hitting people."]]},
        {"act": "gauntley", "do": "reset"},
        {"emote": "gauntley", "text": "!"},
        {"walk": "player", "to": [53, 6], "speed": 3},
        {"face": "gauntley", "to": "player"},
        {"face": "player", "dir": "right"},
        {"talk": [["gauntley", "Oi. You there, with the terrifying stick."],
                  ["gauntley", "You've the look of a lad who's slain a dragon or two."],
                  ["derrick", "...There's no such thing as dragons."],
                  ["gauntley", "Course not. I killed the last one."],
                  ["gauntley", "Tell you what. One pass, you and me. Give it everything you've got, and I'll try to survive."]]},
        {"hint": "In a fight: Strike to swing (or just click who to hit). Brace halves the next blow and gets your breath back."},
        {"battle": "spar", "win": [], "lose": []},
        {"act": "gauntley", "do": "raise"},
        {"talk": [["gauntley", "Did you see that? Did everyone see that? Bested! By a child! With a stick!"],
                  ["gauntley", "What do they call you, champion?"]]},
        {"act": "gauntley", "do": "reset"},
        {"talk": [["derrick", "Derrick."], ["gauntley", "Derrick. I'll remember that."],
                  ["gauntley", "Here's the whole secret, and don't tell the other knights. Shield up. Chin down. And never let a bully see you're scared."],
                  ["derrick", "Shield up. Chin down."]]},
        {"act": "gauntley", "do": "nod", "wait": True},
        {"talk": [["gauntley", "That's it. That's exactly it."]]},
        {"zoom": 1.0, "time": 1.0},
        {"sound": "The church bell, far off. Six strokes."},
        {"talk": [["gauntley", "And that's me summoned. Duty, lad. It's mostly standing about in the rain."]]},
        {"hide": "gauntley", "wait": False},
        {"hide": "horse"},
        {"show": "gauntley_rider"},
        {"walk": "gauntley_rider", "path": [[57, 6], [67, 6]], "speed": 5, "wait": False, "direct": True},
        {"camera": "gauntley_rider", "time": 0.6},
        {"wait": 2.0},
        {"hide": "gauntley_rider"},
        {"camera": "player", "time": 1.0},
        {"caption": "He watched until there was nothing left to watch."},
    ],
    "autumn_home": [
        {"sound": "A woman's voice, calling a name."},
        {"camera": "mother9", "time": 1.0},
        {"talk": [["mother9", "Derrick! There you are. Supper, and then bed."],
                  ["derrick", "Mam. I beat a knight."],
                  ["mother9", "Did you, now."],
                  ["father9", "The big one on the horse? Should I be worried for my job?"],
                  ["mother9", "Wash the knight off your hands before you touch my bread."]]},
        {"camera": [60, 2], "time": 1.6},
        {"wait": 0.6},
        {"talk": [["derrick", "Da. Who's that for? On the hill."],
                  ["father9", "Nobody. Not since before you were born. Harrowgate's not that kind of place."]]},
        {"camera": "player", "time": 1.0},
        {"walk": "mother9", "to": [67, 6], "speed": 3, "wait": False},
        {"walk": "father9", "to": [67, 7], "speed": 3},
        {"hide": "mother9", "wait": False},
        {"hide": "father9"},
        {"hint": "Home is down the road."},
    ],
    "autumn_outro": [
        {"caption": "He left the stick by the door, for the morning.", "hold": 2.6},
    ],
}
STAGES.append(s)

# ============================================================== II. That Night
s = base("s02_that_night", "hamlet_outskirts",
         name="Harrowgate", chapter="II.  That Night", age="nine",
         tint="#2c3150", weather="", start_facing="down",
         derrick={"form": "child", "level": 1},
         props={"1": {"art": "prop/hatch", "at": [8, 17]}},
         lights=[{"id": "torch1", "at": [0, 9], "color": "#ff7a2a", "energy": 0.0, "scale": 2.6, "flicker": True},
                 {"id": "torch2", "at": [0, 10], "color": "#ff7a2a", "energy": 0.0, "scale": 2.6, "flicker": True},
                 {"id": "far", "at": [1, 1], "color": "#ff6a20", "energy": 0.0, "scale": 4.0, "flicker": True},
                 {"id": "next_door", "at": [10, 3], "color": "#ff7020", "energy": 0.0, "scale": 4.5, "flicker": True},
                 {"id": "home", "at": [5, 3], "color": "#ffb060", "energy": 0.55, "scale": 2.2, "flicker": True}],
         fx=[{"kind": "smoke", "at": [1, 0]}, {"kind": "smoke", "at": [2, 1]}],
         lines={"a": {"y": 8}, "b": {"y": 13}, "c": {"y": 16}},
         triggers={"a": "road", "b": "yard", "c": "cellar"},
         cast={"M": {"id": "mother", "at": [5, 5], "hidden": True},
               "F": {"id": "father", "at": [5, 5], "hidden": True},
               "R": {"id": "raider1", "cast": "raider", "at": [0, 9], "hidden": True, "tint": "#161412", "facing": "right"},
               "S": {"id": "raider2", "cast": "raider", "at": [0, 10], "hidden": True, "tint": "#161412", "facing": "right"},
               "T": {"id": "raider3", "cast": "raider", "at": [1, 8], "hidden": True, "tint": "#161412", "facing": "right"}},
         on_enter="night")
s["scripts"] = {
    "night": [
        {"card": "That Night", "sub": "", "hold": 1.6},
        {"sound": "A dog barking. Then another."},
        {"wait": 1.8},
        {"sound": "Then none."},
        {"wait": 1.4},
        {"light": "far", "energy": 1.0, "time": 2.5},
        {"light": "torch1", "energy": 1.2, "time": 2.5},
        {"light": "torch2", "energy": 1.2, "time": 2.5},
        {"tint": "#3c2d33", "time": 2.5},
        {"sound": "Shouting. Far away, and then not far."},
        {"wait": 0.8},
        {"shake": 5},
        {"show": "mother"},
        {"walk": "mother", "to": [6, 6], "speed": 7},
        {"face": "mother", "to": "player"},
        {"talk": [["mother", "Derrick. Up. Now. Not a word."]]},
        {"show": "father"},
        {"talk": [["father", "Maren. The old cellar, by the well."],
                  ["mother", "Hob—"],
                  ["father", "The cellar. Go. I'll be behind you."]]},
        {"sound": "Something heavy hits a door, two houses down."},
        {"shake": 10},
        {"flash": "#e0701f", "time": 0.3},
        {"light": "next_door", "energy": 1.5, "time": 1.2},
        {"walk": "mother", "path": [[6, 8], [5, 8]], "speed": 6},
        {"face": "mother", "to": "player"},
        {"hint": "Follow your mother."},
    ],
    "road": [
        {"camera": [2, 9], "time": 0.8, "wait": False},
        {"show": "raider1", "wait": False}, {"show": "raider2", "wait": False}, {"show": "raider3"},
        {"walk": "raider1", "to": [3, 9], "speed": 1.5, "wait": False, "direct": True},
        {"walk": "raider2", "to": [2, 10], "speed": 1.5, "wait": False, "direct": True},
        {"caption": "Men on the road. No colours, no banners. Just torches, and one of them laughing at something."},
        {"walk": "father", "path": [[5, 7], [4, 7]], "speed": 5, "direct": True},
        {"face": "father", "dir": "left"},
        {"talk": [["father", "Go on, Maren. Go!"]]},
        {"camera": "player", "time": 0.6},
        {"walk": "mother", "path": [[5, 11], [5, 12]], "speed": 7, "wait": False},
        {"talk": [["mother", "Derrick. Now."]]},
        {"walk": "father", "to": [3, 9], "speed": 4, "wait": False, "direct": True},
    ],
    "yard": [
        {"walk": "mother", "path": [[5, 15], [7, 15], [7, 16]], "speed": 7},
        {"face": "mother", "to": "player"},
        {"hint": "The cellar hatch is by the well."},
    ],
    "cellar": [
        {"face": "mother", "to": "player"},
        {"camera": "mother", "time": 0.8, "wait": False},
        {"zoom": 1.45, "time": 1.6},
        {"talk": [["mother", "Down you go. Quick, now."],
                  ["mother", "You count for me. You count to a thousand, and you don't stop. Not for anything. Not for anyone."],
                  ["derrick", "Mam—"], ["mother", "Count."]]},
        {"fade": "out", "time": 0.5},
        {"slats": True},
        {"caption": "One.", "hold": 1.2},
        {"caption": "Two.", "hold": 1.1},
        {"caption": "Three.", "hold": 1.0},
        {"sound": "The door gives."},
        {"slats_shadow": 1.0},
        {"caption": "Fourteen. Fifteen.", "hold": 1.4},
        {"sound": "His father's voice. Then not."},
        {"slats_shadow": 1.6, "dir": "left"},
        {"caption": "Forty.", "hold": 1.4},
        {"sound": "Boots. A lot of boots. A man laughing at something."},
        {"slats_shadow": 0.9},
        {"slats_shadow": 1.3, "dir": "left"},
        {"caption": "Two hundred and six.", "hold": 1.6},
        {"sound": "His mother, saying his name. Once."},
        {"wait": 1.6},
        {"caption": "Three hundred.", "hold": 1.6},
        {"sound": "Fire. The sound fire makes when it has everything it wants."},
        {"caption": "Six hundred and eleven.", "hold": 1.6},
        {"caption": "Nine hundred and ninety-nine.", "hold": 1.8},
        {"caption": "A thousand.", "hold": 2.4},
        {"wait": 1.4},
        {"caption": "Nobody told him to stop. So he started again at one."},
        {"next": True},
    ],
}
STAGES.append(s)

# ============================================================== III. Dawn
s = base("s03_dawn", "village_dawn",
         name="Harrowgate", chapter="III. Dawn", age="nine",
         tint="#a49d94", weather="ash", start_facing="left",
         derrick={"form": "child", "level": 1},
         depth=[{"art": "fore/dawn_fore", "scale": 0.8, "speed": 1.3}],
         mist=[{"y": 0, "h": 260, "speed": 0.6, "alpha": 0.3, "color": "#b8b0a8"}],
         props={"7": {"art": "prop/shroud", "at": [[56, 5], [57, 5]]}},
         fx=[{"kind": "smoke", "at": [27, 1]}, {"kind": "smoke", "at": [35, 1]}, {"kind": "smoke", "at": [44, 2]},
             {"kind": "smoke", "at": [35, 9]}, {"kind": "smoke", "at": [40, 9]}, {"kind": "smoke", "at": [47, 10]},
             {"kind": "embers", "at": [36, 9]}, {"kind": "embers", "at": [28, 2]}],
         lines={"a": {"x": 63}, "b": {"x": 58}, "c": {"x": 36}, "d": {"x": 16}},
         triggers={"a": "stick", "b": "shrouds", "c": "gauntley", "d": "cart"},
         cast={"S": {"id": "sword", "at": [62, 6], "solid": False},
               "R": {"id": "gauntley_rider", "at": [21, 6], "hidden": True},
               "Q": {"id": "rider", "at": [21, 7], "hidden": True},
               "G": {"id": "gauntley", "at": [30, 6], "hidden": True},
               "C": {"id": "crow", "at": [33, 4], "hidden": True, "solid": False}},
         on_enter="dawn", on_exit="leave")
s["level"]["show"] = "village_burned"
s["level"]["glow"] = "village_embers"
s["scripts"] = {
    "dawn": [
        {"card": "Dawn", "sub": "", "hold": 1.6},
        {"sound": "Birds. As if nothing had happened."},
        {"caption": "The hatch was heavier than it had been. Something had fallen across it. It took him most of the morning."},
    ],
    "stick": [
        {"walk": "player", "to": [62, 7], "speed": 3},
        {"face": "player", "dir": "up"},
        {"hide": "sword"},
        {"caption": "His stick. Someone had trodden on it. He picked it up anyway."},
    ],
    "shrouds": [
        {"camera": [56, 5], "time": 1.4},
        {"wait": 0.8},
        {"caption": "On the green, where the knight had let him win. Someone had covered them. He did not lift the cloth."},
        {"caption": "He knew the shoes."},
    ],
    "gauntley": [
        {"sound": "Horses. Coming hard."},
        {"show": "gauntley_rider", "wait": False},
        {"show": "rider"},
        {"camera": [31, 6], "time": 1.2, "wait": False},
        {"walk": "rider", "to": [29, 7], "speed": 6, "wait": False, "direct": True},
        {"walk": "gauntley_rider", "to": [30, 6], "speed": 6, "direct": True},
        {"hide": "gauntley_rider", "wait": False},
        {"teleport": "gauntley", "to": [30, 6]},
        {"show": "gauntley"},
        {"walk": "gauntley", "to": [34, 6], "speed": 3},
        {"face": "gauntley", "to": "player"},
        {"camera": [35, 6], "time": 1.0, "wait": False},
        {"zoom": 1.3, "time": 1.2},
        {"talk": [["gauntley", "God's teeth."],
                  ["gauntley", "...Lad. Lad, look at me. Are you hurt?"],
                  ["gauntley", "Derrick. It's Derrick, isn't it."],
                  ["derrick", "..."],
                  ["gauntley", "Is there anyone— is there anyone else?"],
                  ["derrick", "..."],
                  ["gauntley", "No. No, of course not."],
                  ["rider", "Ser. Tracks on the north road. A lot of horses. Fresh."],
                  ["gauntley", "Whose?"],
                  ["rider", "No banners, Ser. Not a scrap of colour on any of them."],
                  ["gauntley", "Men with no banners."]]},
        {"wait": 0.6},
        {"talk": [["gauntley", "Listen to me. The men who did this are still on the road, and I am going to catch them. You stay here. Right here, by the well."],
                  ["gauntley", "I'll come back for you. I swear it on my name."],
                  ["derrick", "...Shield up. Chin down."]]},
        {"act": "gauntley", "do": "nod", "wait": True},
        {"talk": [["gauntley", "That's it. That's exactly it."]]},
        {"zoom": 1.0, "time": 0.8},
        {"walk": "gauntley", "to": [30, 6], "speed": 4},
        {"hide": "gauntley"},
        {"teleport": "gauntley_rider", "to": [30, 6]},
        {"show": "gauntley_rider"},
        {"walk": "gauntley_rider", "to": [18, 6], "speed": 6, "wait": False, "direct": True},
        {"walk": "rider", "to": [18, 7], "speed": 6, "direct": True},
        {"hide": "gauntley_rider", "wait": False},
        {"hide": "rider"},
        {"walk": "player", "to": [31, 6], "speed": 2},
        {"face": "player", "dir": "up"},
        {"pose": "player", "art": "char/derrick_child_sit_field"},
        {"camera": [31, 5], "time": 1.0, "wait": False},
        {"zoom": 1.6, "time": 2.0, "wait": True},
        {"tint": "#b98a64", "time": 2.5, "wait": True},
        {"caption": "He waited.", "hold": 2.2},
        {"tint": "#2c3350", "time": 2.5, "wait": True},
        {"caption": "The first night.", "hold": 2.0},
        {"tint": "#9c9790", "time": 2.0},
        {"show": "crow"},
        {"caption": "The second day. Crows.", "hold": 2.2},
        {"tint": "#262c44", "time": 2.0, "wait": True},
        {"weather": "rain"},
        {"caption": "The second night. Rain.", "hold": 2.2},
        {"tint": "#a8a39c", "time": 2.0, "wait": True},
        {"weather": "ash"},
        {"hide": "crow"},
        {"caption": "The third day.", "hold": 2.2},
        {"wait": 1.4},
        {"caption": "Ser Gauntley did not come back."},
        {"pose": "player", "art": ""},
        {"hint": "The road goes west."},
    ],
    "cart": [
        {"camera": [11, 8], "time": 1.2},
        {"caption": "His father's cart, where his father had left it. The wheel was still off."},
        {"camera": "player", "time": 0.8},
    ],
    "leave": [
        {"caption": "On the fourth morning, he stopped waiting."},
    ],
}
STAGES.append(s)

# ============================================================== IV. Ashford
LANTERNS = [[8, 3], [11, 3], [8, 7], [11, 7], [8, 9], [11, 9], [8, 14], [11, 14]]
s = base("s04_ashford", "mirewatch_gate",
         name="Ashford", chapter="IV.  Ashford", age="thirteen",
         tint="#76808f", weather="rain", start_facing="up",
         derrick={"form": "youth", "level": 3}, give={"rag": 1},
         growth_text="Derrick, thirteen. Hunger has taught him to fight dirty.",
         lights=[{"id": "l%d" % i, "at": a, "color": "#ff9a48", "energy": 0.7, "scale": 1.6, "flicker": True}
                 for i, a in enumerate(LANTERNS)] +
                [{"id": "window", "at": [13, 0], "color": "#ffb060", "energy": 1.0, "scale": 2.6, "flicker": True}],
         lines={"a": {"y": 15}, "b": {"y": 9}, "c": {"y": 3}},
         triggers={"a": "marsh", "b": "alms", "c": "window"},
         cast={"B": {"id": "monk", "at": [11, 8], "facing": "left"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "Ashford", "sub": "Four winters later.", "hold": 2.4},
        {"growth": True},
        {"sound": "Rain on black water. Frogs. Somewhere past the wall, a bell for vespers."},
    ],
    "marsh": [
        {"caption": "He had walked for four winters. He had worn out three pairs of shoes, and then stopped needing them."},
    ],
    "alms": [
        {"walk": "player", "to": [10, 8], "speed": 3},
        {"face": "player", "dir": "right"},
        {"face": "monk", "to": "player"},
        {"talk": [["derrick", "Please, Brother."],
                  ["monk", "Alms are for the parish's own, boy. Which parish are you?"],
                  ["derrick", "Harrowgate."],
                  ["monk", "There's no Harrowgate."],
                  ["monk", "...Not any more. Move along."]]},
        {"caption": "He had stopped counting the days. He had not stopped counting."},
        {"sound": "A cart, rumbling for the gate. The Brother turns to shout at the carter."},
        {"face": "monk", "dir": "down"},
        {"hint": "The gate is open behind the cart."},
    ],
    "window": [
        {"camera": [13, 0], "time": 1.2},
        {"wait": 0.4},
        {"caption": "Through the glass: a family at table. A father tearing bread. A boy about his age, laughing at nothing."},
        {"caption": "Three loaves. He counted.", "hold": 2.4},
        {"camera": "player", "time": 0.8},
    ],
}
STAGES.append(s)

# ============================================================== V. The Butcher's Steps (Ashford market)
s = base("s05_butchers_steps", "butchers_steps",
         name="Ashford", chapter="V.   The Butcher's Steps", age="thirteen",
         tint="#7a8494", weather="rain", start_facing="up",
         derrick={"form": "youth", "level": 3},
         props={"2": {"art": "prop/bread_cart", "at": [7, 8]}},
         lines={"a": {"y": 15}, "b": {"y": 10}},
         triggers={"a": "market", "b": "bread"},
         cast={"K": {"id": "baker", "at": [5, 9], "facing": "left"},
               "C": {"id": "carter", "cast": "villager", "at": [4, 9], "facing": "right"},
               "D": {"id": "dog", "at": [16, 1], "hidden": True, "facing": "left"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"sound": "Rain on slate. Cartwheels. A market packing up."},
    ],
    "market": [
        {"camera": [9, 3], "time": 1.4},
        {"caption": "The Butcher's Steps. Three ropes on the scaffold, empty today. Tomorrow was a market day."},
        {"camera": "player", "time": 1.0},
    ],
    "bread": [
        {"sound": "The baker, arguing with a carter about a horse."},
        {"talk": [["baker", "Lame! You sold me a lame horse and you know it!"], ["carter", "It weren't lame when it left me."]]},
        {"walk": "player", "to": [8, 9], "speed": 3},
        {"face": "player", "dir": "left"},
        {"caption": "He took one. It was the easiest thing he had ever done."},
        {"give": "bread", "n": 1},
        {"emote": "baker", "text": "!"},
        {"act": "baker", "do": "attack"},
        {"talk": [["baker", "Oi! THIEF! Stop him!"]]},
        {"shake": 5},
        {"walk": "player", "path": [[12, 9], [14, 9], [14, 5]], "speed": 7},
        {"sound": "Rain on the hooks of the butchers' row. His own breathing."},
        {"wait": 0.6},
        {"sound": "A growl."},
        {"face": "player", "dir": "up"},
        {"show": "dog"},
        {"camera": [15, 3], "time": 0.7, "wait": False},
        {"zoom": 1.35, "time": 0.7},
        {"walk": "dog", "to": [15, 3], "speed": 2},
        {"caption": "It was thinner than he was. It wanted the bread more than he did. Neither of them was going to give it up."},
        {"battle": "dog", "win": [{"fall": "dog"}, {"caption": "He ate beside it, in the rain. He shared none of it."}]},
        {"hint": "The butchers' row runs north, out of the market."},
    ],
}
STAGES.append(s)

# ============================================================== VI. The Ostry Farm
s = base("s06_ostry_farm", "sunk_furrows",
         name="the Ostry farm", chapter="VI.  The Ostry Farm", age="sixteen",
         tint="#f2dcb0", weather="", start_facing="up",
         derrick={"form": "lad", "level": 5}, give={"rag": 1},
         growth_text="Derrick, sixteen. He has grown into his hands.",
         lines={"a": {"y": 16}, "b": {"y": 12}, "c": {"y": 8}},
         triggers={"a": "hire", "b": "hild", "c": "accused"},
         cast={"O": {"id": "ostry", "at": [3, 15], "facing": "right"},
               "H": {"id": "hild", "at": [5, 10], "facing": "right"},
               "E": {"id": "edric", "at": [12, 7], "facing": "left", "steps_aside": True},
               "W": {"id": "wat", "at": [13, 8], "facing": "left", "steps_aside": True},
               "L": {"id": "ostry_late", "cast": "ostry", "at": [14, 6], "hidden": True, "facing": "left"}},
         on_enter="intro", on_exit="leave")
s["scripts"] = {
    "intro": [
        {"card": "The Ostry Farm", "sub": "Three years on. Harvest, and the river up over the low fields.", "hold": 2.6},
        {"growth": True},
        {"sound": "Scythes. Water in the ditches. Somebody whistling the same four notes, over and over."},
    ],
    "hire": [
        {"face": "ostry", "to": "player"},
        {"talk": [["ostry", "You the one from the hiring fair?"], ["derrick", "Yes."], ["ostry", "You're thin."],
                  ["derrick", "I'm strong."],
                  ["ostry", "You'd better be. Penny a day and whatever's in the pot. You sleep in the mill. You don't come in the house."],
                  ["derrick", "Yes, sir."]]},
        {"hide": "ostry"},
    ],
    "hild": [
        {"walk": "player", "to": [6, 11], "speed": 3},
        {"face": "player", "dir": "left"},
        {"face": "hild", "to": "player"},
        {"talk": [["hild", "Here. Eat. You're all elbows."], ["derrick", "Thank you."],
                  ["hild", "Ha. Manners. Where'd you get those?"], ["derrick", "My mam."],
                  ["hild", "...Well. She did right by you."]]},
        {"fade": "out", "time": 1.0},
        {"caption": "The harvest took eleven days. He counted every one.", "center": True},
        {"caption": "On the sixth, the youngest boy showed him how to tie a sheaf properly.", "center": True},
        {"caption": "On the ninth, she let him eat at the table.", "center": True},
        {"caption": "He didn't say anything. He was afraid that if he said anything, it would stop.", "center": True},
        {"tint": "#ecc9a0", "time": 0.1},
        {"fade": "in", "time": 1.2},
    ],
    "accused": [
        {"camera": [12, 7], "time": 0.8},
        {"talk": [["edric", "Da's knife is gone. The good one, with the horn handle."],
                  ["wat", "It was on the block this morning. Now it's not."]]},
        {"prompt": ["edric", "Turn out your pack."], "choice": [
            {"text": "\"I didn't take it.\"", "then": [{"talk": [["edric", "Course you'd say that."]]}]},
            {"text": "Turn out the pack.", "then": [
                {"caption": "He turned it out. A shirt. The stick. Half a heel of bread. No knife."},
                {"talk": [["wat", "He's hidden it, then. Or sold it."]]}]}]},
        {"talk": [["edric", "We took you in. We fed you."], ["derrick", "I worked."]]},
        {"battle": "ostry",
         "win": [{"caption": "He won.", "hold": 1.8}, {"caption": "It changed nothing."}],
         "lose": [{"fall": "player"}, {"caption": "He lost.", "hold": 1.8}, {"caption": "It changed nothing."}, {"rise": "player"}]},
        {"show": "ostry_late"},
        {"walk": "ostry_late", "to": [13, 6], "speed": 3},
        {"talk": [["ostry_late", "I don't care who hit who. Get your things."],
                  ["ostry_late", "Eleven days. There's your pennies. We're square."],
                  ["derrick", "I didn't take it."],
                  ["ostry_late", "Then you've nothing to worry about, have you. Go on."]]},
        {"camera": "hild", "time": 1.4},
        {"caption": "She watched from the field's edge. She didn't say anything either."},
        {"walk": "edric", "to": [6, 12], "speed": 3, "wait": False},
        {"walk": "wat", "to": [7, 12], "speed": 3, "wait": False},
        {"walk": "ostry_late", "to": [8, 11], "speed": 3},
        {"face": "edric", "dir": "up"}, {"face": "wat", "dir": "up"}, {"face": "ostry_late", "dir": "up"},
        {"camera": "player", "time": 0.8},
        {"hint": "The causeway goes on, over the floods."},
    ],
    "leave": [
        {"caption": "The knife turned up in the spring, under the woodpile. Nobody ever told him."},
    ],
}
STAGES.append(s)

# ============================================================== VII. The Levy (night before Wendmere)
s = base("s07_levy_camp", "blackwood_camp",
         name="the levy camp", chapter="VII. The Levy", age="twenty",
         tint="#4c5168", weather="", start_facing="right",
         derrick={"form": "man", "level": 7}, give={"rag": 1},
         growth_text="Derrick, twenty. A levy spear, and a lord's colours he never learned the name of.",
         lights=[{"id": "fire1", "at": [6, 6], "color": "#ff8a3a", "energy": 1.2, "scale": 3.4, "flicker": True},
                 {"id": "fire2", "at": [14, 5], "color": "#ff8a3a", "energy": 1.2, "scale": 3.4, "flicker": True},
                 {"id": "fire3", "at": [13, 14], "color": "#ff6a20", "energy": 0.9, "scale": 3.0, "flicker": True},
                 {"id": "fire4", "at": [6, 13], "color": "#ff6a20", "energy": 0.9, "scale": 3.0, "flicker": True}],
         fx=[{"kind": "embers", "at": [6, 6]}, {"kind": "embers", "at": [14, 5]},
             {"kind": "smoke", "at": [6, 5]}, {"kind": "smoke", "at": [14, 4]}],
         lines={"a": {"x": 6}, "b": {"x": 10}, "c": {"x": 14}},
         triggers={"a": "spear", "b": "fire", "c": "aldo"},
         cast={"P": {"id": "sergeant", "at": [9, 8], "facing": "left"},
               "S": {"id": "soldier1", "cast": "soldier", "at": [5, 7], "facing": "right"},
               "T": {"id": "soldier2", "cast": "soldier", "at": [7, 7], "facing": "left"},
               "U": {"id": "soldier3", "cast": "soldier_b", "at": [12, 5], "facing": "right"},
               "A": {"id": "aldo", "at": [15, 6], "facing": "left"},
               "M": {"id": "soldier4", "cast": "man_at_arms", "at": [17, 7], "facing": "left"}},
         on_enter="intro", on_exit="horns")
s["scripts"] = {
    "intro": [
        {"card": "Wendmere Field", "sub": "Four years on. The night before.", "hold": 2.6},
        {"growth": True},
        {"sound": "Two hundred men pretending to sleep. A whetstone, somewhere, that never stops."},
    ],
    "spear": [
        {"face": "sergeant", "to": "player"},
        {"talk": [["sergeant", "Name?"], ["derrick", "Derrick."], ["sergeant", "From?"], ["derrick", "...Nowhere."],
                  ["sergeant", "Good. Nowhere's got no lord to whinge to. Harl's company. Front rank."],
                  ["sergeant", "That's a spear. The pointy end goes toward the other lot. Any questions?"],
                  ["derrick", "Which lot is the other lot?"],
                  ["sergeant", "The ones that aren't us. Next!"]]},
    ],
    "fire": [
        {"talk": [["soldier3", "...I'm telling you. Gauntley. He's riding with the lord's van."],
                  ["soldier1", "The Gauntley? Out of the songs?"],
                  ["soldier3", "Saw his horse myself. Big grey thing, eats like a bishop."]]},
        {"act": "player", "do": "cower"},
        {"wait": 0.6},
        {"act": "player", "do": "reset"},
        {"caption": "He could have walked thirty yards and seen him. He did not go to look."},
    ],
    "aldo": [
        {"face": "aldo", "to": "player"},
        {"talk": [["aldo", "You. Harrowgate, isn't it? I heard you tell Pike nowhere. That's a lie, but it's a good one."],
                  ["aldo", "Aldo. Wendmere born. Sit, sit, the fire's not mine."],
                  ["aldo", "Two daughters. Bess, and little Aldo, who hates it. And a miller who'll have my roof if I don't come home with the purse."],
                  ["derrick", "Then come home with the purse."],
                  ["aldo", "Ha! That's the plan. Stick by me tomorrow, Harrowgate. Two's harder to kill than one."],
                  ["derrick", "...All right."]]},
        {"caption": "He had not said all right to anyone in seven years. It came out strange."},
    ],
    "horns": [
        {"sound": "Horns, before light. Somebody being sick behind a wagon."},
        {"caption": "The battle at Wendmere lasted until a little after noon."},
    ],
}
STAGES.append(s)

# ============================================================== VIII. Wendmere
s = base("s08_wendmere", "forest_road",
         name="Wendmere", chapter="VIII. Wendmere", age="twenty",
         tint="#9aa196", weather="fog", start_facing="right",
         derrick={"form": "man", "level": 7},
         mist=[{"y": 0, "h": 240, "speed": 0.6, "alpha": 0.28, "color": "#c8ccc4"}],
         props={"1": {"art": "prop/fallen", "at": [[6, 8], [13, 4], [19, 8], [31, 8], [44, 4], [47, 8], [58, 8]]},
                "2": {"art": "prop/spears", "at": [[9, 4], [36, 8], [53, 4]]},
                "3": {"art": "prop/lord_banner", "at": [[42, 8]]}},
         lines={"a": {"x": 10}, "b": {"x": 24}, "c": {"x": 37}, "d": {"x": 52}},
         triggers={"a": "field", "b": "aldo", "c": "gauntley", "d": "looter"},
         cast={"L": {"id": "aldo", "at": [27, 4], "down": True},
               "P": {"id": "looter", "at": [57, 6], "facing": "left", "steps_aside": True},
               "C": {"id": "crow1", "cast": "crow", "at": [40, 4], "solid": False},
               "D": {"id": "crow2", "cast": "crow", "at": [59, 7], "solid": False, "facing": "left"},
               "R": {"id": "gauntley_rider", "at": [52, 5], "hidden": True, "facing": "left"},
               "Q": {"id": "rider", "at": [52, 6], "hidden": True, "facing": "left"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "Wendmere", "sub": "The morning after.", "hold": 2.4},
        {"sound": "Nothing. Then a crow, and another, arguing over something."},
    ],
    "field": [
        {"camera": [16, 6], "time": 1.6},
        {"caption": "They had told him which side he was on. They had not told him what it was for."},
        {"camera": "player", "time": 1.0},
    ],
    "aldo": [
        {"sound": "Someone breathing wrong."},
        {"camera": "aldo", "time": 1.0},
        {"talk": [["aldo", "You. Are you— Harrowgate. It's you. I told you. Two's harder."]]},
        {"prompt": ["aldo", "Sit with me. Just a bit. I don't— I don't want to go by myself."], "choice": [
            {"text": "Sit with him.", "then": [
                {"add": "defiance", "n": 1},
                {"walk": "player", "to": [27, 5], "speed": 2},
                {"face": "player", "dir": "up"},
                {"fade": "out", "time": 1.2},
                {"caption": "He sat with him until he stopped talking. It did not take long.", "center": True},
                {"caption": "Aldo told him about his daughters again, and the miller, and the roof. He told it all as if Derrick could take it somewhere.", "center": True},
                {"fade": "in", "time": 1.2}]},
            {"text": "Keep walking.", "then": [
                {"add": "complicity", "n": 1},
                {"talk": [["aldo", "Please—"]]},
                {"caption": "He didn't look back. He was getting good at it."}]}]},
    ],
    "gauntley": [
        {"sound": "Horses. A lot of them. Victors don't hurry."},
        {"walk": "player", "to": [37, 7], "speed": 5},
        {"face": "player", "dir": "right"},
        {"show": "gauntley_rider", "wait": False},
        {"show": "rider"},
        {"camera": [41, 6], "time": 1.0, "wait": False},
        {"walk": "rider", "to": [41, 6], "speed": 3, "wait": False, "direct": True},
        {"walk": "gauntley_rider", "to": [40, 5], "speed": 3, "direct": True},
        {"hide": "crow1", "wait": False},
        {"zoom": 1.2, "time": 0.6},
        {"talk": [["gauntley_rider", "Clear the road there, friend! Wounded coming through."],
                  ["derrick", "Ser Gauntley."],
                  ["gauntley_rider", "Aye, that's me. God keep you, son."]]},
        {"walk": "gauntley_rider", "path": [[40, 5], [0, 5]], "speed": 3, "wait": False, "direct": True},
        {"walk": "rider", "path": [[41, 6], [0, 6]], "speed": 3, "wait": False, "direct": True},
        {"camera": "gauntley_rider", "time": 0.8},
        {"wait": 3.0},
        {"hide": "gauntley_rider", "wait": False},
        {"hide": "rider"},
        {"camera": "player", "time": 1.2},
        {"zoom": 1.0, "time": 0.6},
        {"caption": "He had been nine. He had been small. It was a long time ago, and there had been a great many villages."},
        {"caption": "Shield up. Chin down.", "hold": 2.4},
    ],
    "looter": [
        {"camera": "looter", "time": 0.8},
        {"talk": [["looter", "These are mine. Find your own dead."], ["derrick", "I don't want anything."],
                  ["looter", "Everybody wants something. You want those boots to stay on your feet, for one."],
                  ["looter", "They're good boots."]]},
        {"battle": "looter", "win": [{"fall": "looter"}, {"hide": "crow2"},
                                     {"caption": "The man had eleven pairs of boots in his sack. None of them fit."},
                                     {"caption": "He took the knife instead.", "hold": 2.2}]},
    ],
}
STAGES.append(s)

# ============================================================== IX. The Coldharbour Road (gallows bend)
s = base("s09_coldharbour_road", "gallows_bend",
         name="the Coldharbour road", chapter="IX.  The Coldharbour Road", age="twenty-one",
         tint="#c4ccd8", weather="snow", start_facing="right",
         derrick={"form": "man", "level": 8}, give={"rag": 1},
         growth_text="Derrick, twenty-one. Nothing new. Less of everything.",
         props={"4": {"art": "prop/sons_banner", "at": [13, 7], "examine": "notice"}},
         lines={"a": {"x": 4}, "b": {"x": 11}, "c": {"x": 17}},
         triggers={"a": "cold", "b": "gibbet", "c": "eyes"},
         cast={"C": {"id": "crow", "at": [11, 6], "solid": False, "facing": "left"},
               "W": {"id": "wolf_eyes", "cast": "wolf", "at": [18, 13], "hidden": True, "facing": "left", "tint": "#3a3e48"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "The Coldharbour Road", "sub": "The winter after.", "hold": 2.4},
        {"growth": True},
    ],
    "cold": [
        {"caption": "He had not eaten in four days. He had stopped counting those, too. That frightened him more than the hunger did."},
    ],
    "gibbet": [
        {"camera": [12, 7], "time": 1.2},
        {"caption": "A gallows at the bend in the road. The ropes were empty. The notice nailed to the post was new."},
        {"run": "notice"},
        {"sound": "A crow, complaining."},
        {"hide": "crow"},
        {"camera": "player", "time": 0.8},
    ],
    "notice": [
        {"caption": "BY WARRANT, AND IN FULL SATISFACTION OF CONTRACT: THE SONS OF ST. JACK.  TERMS HONOURED.  NO FURTHER CLAIMS."},
        {"caption": "Someone had drawn a coin with a nail through it. Someone had taken care over it."},
    ],
    "eyes": [
        {"show": "wolf_eyes"},
        {"camera": [17, 12], "time": 0.8},
        {"caption": "Eyes, in the trees below the road. They kept pace with him, and did not hurry. They didn't need to."},
        {"hide": "wolf_eyes"},
        {"camera": "player", "time": 0.8},
    ],
}
STAGES.append(s)

# ============================================================== X. Thornwake
s = base("s10_thornwake", "thornwake",
         name="the Thornwake", chapter="X.   The Thornwake", age="twenty-one",
         tint="#8a93a8", weather="snow", start_facing="right",
         derrick={"form": "man", "level": 8},
         lights=[{"id": "campglow", "at": [19, 10], "color": "#ff7a2a", "energy": 0.0, "scale": 6.0, "flicker": True}],
         lines={"a": {"x": 5}, "b": {"x": 11}, "c": {"x": 16}},
         triggers={"a": "wolves", "b": "brook", "c": "collapse"},
         cast={"W": {"id": "wolf1", "cast": "wolf", "at": [8, 6], "hidden": True, "facing": "left"},
               "X": {"id": "wolf2", "cast": "wolf", "at": [9, 12], "hidden": True, "facing": "left"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "The Thornwake", "sub": "", "hold": 1.8},
        {"sound": "Snow on thorns. Water, somewhere ahead, loud and black."},
    ],
    "wolves": [
        {"sound": "Nothing. The wood went quiet all at once."},
        {"wait": 1.0},
        {"face": "player", "dir": "right"},
        {"show": "wolf1", "wait": False},
        {"show": "wolf2"},
        {"camera": [7, 9], "time": 0.7, "wait": False},
        {"walk": "wolf1", "to": [7, 9], "speed": 3, "wait": False, "direct": True},
        {"walk": "wolf2", "to": [8, 10], "speed": 3, "direct": True},
        {"caption": "They had followed him from the gallows. They were as hungry as he was, and there were two of them."},
        {"battle": "wolves", "win": [{"fall": "wolf1"}, {"fall": "wolf2"},
                                     {"caption": "He ate what he could. It was not enough. It was more than he'd had."}]},
    ],
    "brook": [
        {"caption": "He crossed on the fallen tree, the way you cross anything: without looking down."},
    ],
    "collapse": [
        {"walk": "player", "to": [17, 10], "speed": 1.2},
        {"fall": "player"},
        {"shake": 3},
        {"zoom": 1.4, "time": 2.0, "wait": False},
        {"tint": "#4a5468", "time": 2.5, "wait": True},
        {"caption": "He sat down in the snow, which is the one thing you are never supposed to do."},
        {"wait": 1.4},
        {"zoom": 1.0, "time": 1.5, "wait": False},
        {"light": "campglow", "energy": 1.2, "time": 2.5},
        {"camera": [19, 9], "time": 2.2},
        {"sound": "Bells. Far off, and ringing too fast."},
        {"wait": 1.2},
        {"sound": "Smoke on the wind. A city, burning."},
        {"wait": 1.8},
        {"camera": "player", "time": 1.2},
        {"rise": "player"},
        {"caption": "He got up.", "hold": 2.0},
        {"caption": "A burning city meant doors left open.", "hold": 2.4},
        {"tint": "#8a93a8", "time": 1.5},
    ],
}
STAGES.append(s)

# ============================================================== XI. Coldharbour
s = base("s11_coldharbour", "city_road",
         name="Coldharbour", chapter="XI.  Coldharbour", age="twenty-one",
         tint="#3c3648", weather="ash", start_facing="right",
         derrick={"form": "man", "level": 9},
         depth=[{"art": "fore/city_fore", "scale": 1.0, "speed": 1.3}],
         lights=[{"id": "gatefire", "at": [12, 3], "color": "#ff7a2a", "energy": 1.4, "scale": 5.0, "flicker": True},
                 {"id": "fire_a", "at": [27, 2], "color": "#ff7a2a", "energy": 1.3, "scale": 4.5, "flicker": True},
                 {"id": "fire_b", "at": [40, 1], "color": "#ff7a2a", "energy": 1.3, "scale": 4.5, "flicker": True},
                 {"id": "fire_c", "at": [30, 11], "color": "#ff6a20", "energy": 1.0, "scale": 4.0, "flicker": True},
                 {"id": "pyre", "at": [61, 5], "color": "#ff7a2a", "energy": 1.6, "scale": 5.0, "flicker": True},
                 {"id": "torch1", "at": [33, 5], "color": "#ffb060", "energy": 0.8, "scale": 2.0, "flicker": True}],
         fx=[{"kind": "embers", "at": [27, 1]}, {"kind": "smoke", "at": [27, 0]}, {"kind": "embers", "at": [40, 0]},
             {"kind": "smoke", "at": [41, 0]}, {"kind": "embers", "at": [61, 5]}, {"kind": "smoke", "at": [61, 4]},
             {"kind": "smoke", "at": [12, 1]}],
         props={"5": {"art": "prop/sons_banner", "at": [58, 4]}},
         lines={"a": {"x": 6}, "b": {"x": 22}, "c": {"x": 31}, "d": {"x": 52}},
         triggers={"a": "gate", "b": "street", "c": "foragers", "d": "plaza"},
         cast={"F": {"id": "forager1", "cast": "forager", "at": [36, 5], "hidden": True, "facing": "left"},
               "G": {"id": "forager2", "cast": "son_c", "at": [37, 5], "hidden": True, "facing": "left"},
               "K": {"id": "clerk", "at": [38, 6], "hidden": True, "facing": "left"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "Coldharbour", "sub": "The same night.", "hold": 2.4},
        {"sound": "Bells, ringing too fast. Doors giving, one after another, all down the street."},
    ],
    "gate": [
        {"camera": [12, 5], "time": 1.4},
        {"caption": "Carts, left where they'd stood. A city's worth of people had tried to leave by this road, and then thought better of it."},
        {"camera": "player", "time": 1.0},
    ],
    "street": [
        {"camera": [30, 5], "time": 1.6},
        {"caption": "The city was being emptied, house by house, the way you'd empty a cellar."},
        {"camera": "player", "time": 1.0},
    ],
    "foragers": [
        {"walk": "player", "to": [31, 8], "speed": 5},
        {"face": "player", "dir": "right"},
        {"sound": "A door, kicked in. Unhurried voices."},
        {"show": "forager1", "wait": False}, {"show": "forager2", "wait": False}, {"show": "clerk"},
        {"walk": "forager2", "path": [[37, 6], [44, 6]], "speed": 3, "wait": False, "direct": True},
        {"walk": "forager1", "path": [[36, 6], [43, 6]], "speed": 3, "wait": False, "direct": True},
        {"caption": "Men went door to door with sacks and torches. One of them was writing it all down."},
        {"talk": [["clerk", "Pewter, four. Candlesticks, two, brass. One cloak, wool, good. Mark it."]]},
        {"walk": "clerk", "path": [[38, 7], [45, 7]], "speed": 3, "direct": True},
        {"hide": "forager1", "wait": False}, {"hide": "forager2", "wait": False}, {"hide": "clerk"},
    ],
    "plaza": [
        {"camera": [58, 5], "time": 1.4},
        {"caption": "In the square they had built a fire in the pit, and hung a banner over it: a coin with a nail through it."},
        {"caption": "He had seen that coin before, nailed under a gallows. He went the other way, into the alleys."},
        {"camera": "player", "time": 0.8},
        {"hint": "The alleys are east, past the square."},
    ],
}
STAGES.append(s)

# ============================================================== XII. St. Ordric's Ward (the Sons of St. Jack)
s = base("s12_st_ordrics", "st_ordrics_ward",
         name="Coldharbour", chapter="XII. St. Ordric's Ward", age="twenty-one",
         tint="#3a3446", weather="ash", start_facing="up",
         derrick={"form": "man", "level": 9},
         lights=[{"id": "fire1", "at": [17, 19], "color": "#ff7a2a", "energy": 1.2, "scale": 4.0, "flicker": True},
                 {"id": "fire2", "at": [20, 11], "color": "#ff7a2a", "energy": 1.1, "scale": 4.0, "flicker": True},
                 {"id": "mouth", "at": [12, 6], "color": "#ff8a3a", "energy": 0.6, "scale": 3.0, "flicker": True},
                 {"id": "lantern", "at": [11, 3], "color": "#ffb060", "energy": 0.0, "scale": 2.6, "flicker": True}],
         fx=[{"kind": "embers", "at": [17, 18]}, {"kind": "smoke", "at": [17, 17]}, {"kind": "embers", "at": [21, 10]}],
         lines={"a": {"y": 19}, "b": {"y": 15}, "c": {"y": 12}},
         triggers={"a": "sacks", "b": "hide", "c": "cornered"},
         cast={
             "F": {"id": "forager1", "cast": "forager", "at": [20, 20], "hidden": True, "facing": "left"},
             "G": {"id": "forager2", "cast": "son_c", "at": [21, 20], "hidden": True, "facing": "left"},
             "B": {"id": "bearded", "at": [21, 12], "hidden": True, "facing": "left"},
             "W": {"id": "wiry", "at": [14, 17], "hidden": True, "facing": "up"},
             "R": {"id": "grabber", "at": [14, 18], "hidden": True, "facing": "up"},
             "Y": {"id": "bloody", "at": [12, 3], "hidden": True, "facing": "left"},
             "T": {"id": "tall_man", "at": [11, 4], "hidden": True},
             "a1": {"id": "man1", "cast": "son_a", "at": [11, 5], "hidden": True, "facing": "right"},
             "a2": {"id": "man2", "cast": "son_b", "at": [13, 5], "hidden": True, "facing": "left"},
             "a3": {"id": "man3", "cast": "son_c", "at": [12, 6], "hidden": True},
             "a4": {"id": "man4", "cast": "son_a", "at": [13, 6], "hidden": True, "facing": "left"},
             "a5": {"id": "man5", "cast": "son_b", "at": [12, 7], "hidden": True, "facing": "right"}},
         on_enter="intro")
s["scripts"] = {
    "intro": [
        {"card": "St. Ordric's Ward", "sub": "", "hold": 1.8},
        {"sound": "Fewer bells here. Closer fires. Somebody, a long way off, still screaming."},
    ],
    "sacks": [
        {"show": "forager1", "wait": False}, {"show": "forager2"},
        {"camera": [18, 20], "time": 1.0},
        {"caption": "Two more of them, at the end of the lane, sharing a sack between them like a loaf."},
        {"walk": "forager1", "to": [21, 23], "speed": 3, "wait": False, "direct": True},
        {"walk": "forager2", "to": [21, 23], "speed": 3, "direct": True},
        {"hide": "forager1", "wait": False}, {"hide": "forager2"},
        {"camera": "player", "time": 0.8},
    ],
    "hide": [
        {"caption": "He kept to the narrow ways, where the fire hadn't reached and the foragers hadn't bothered. Yet."},
    ],
    "cornered": [
        {"sound": "Boots behind him. Then in front of him."},
        {"show": "bearded", "wait": False},
        {"show": "wiry", "wait": False},
        {"show": "grabber"},
        {"emote": "wiry", "text": "!"},
        {"walk": "player", "path": [[12, 12], [12, 2], [11, 2]], "speed": 6, "direct": True},
        {"face": "player", "dir": "down"},
        {"camera": [11.5, 2.6], "time": 0.8, "wait": False},
        {"caption": "A dead end. A wall of rotten planks, and nothing behind it but more city.", "hold": 2.6},
        {"walk": "bearded", "path": [[12, 12], [12, 4]], "speed": 4, "wait": False, "direct": True},
        {"walk": "wiry", "path": [[14, 12], [12, 12], [12, 3]], "speed": 4, "wait": False, "direct": True},
        {"walk": "grabber", "path": [[14, 12], [12, 12], [12, 5], [11, 5], [11, 3]], "speed": 4, "direct": True},
        {"show": "man1", "wait": False}, {"show": "man2", "wait": False}, {"show": "man3", "wait": False},
        {"show": "man4", "wait": False}, {"show": "man5"},
        {"light": "lantern", "energy": 1.0, "time": 1.0},
        {"zoom": 1.5, "time": 1.4},
        {"act": "player", "do": "guard"},
        {"caption": "The men gathered around him, eyes cold and unblinking. He shrank back into the rotting wooden wall behind him, his knife pointed, shaking at no one in particular."},
        {"talk": [["derrick", "get away from me."]]},
        {"caption": "Derrick managed to breathe without stuttering."},
        {"caption": "The big bearded man to his front just smiled, something strange in his teeth."},
        {"act": "bearded", "do": "raise"},
        {"talk": [["bearded", "Now now. Let's put the knife away lad. There's no need for any kind of trouble here."]]},
        {"hint": "One move. Make it count."},
        {"battle": "alley", "then": []},
        {"caption": "Derrick's head hit the wall. It took a full second for him to realize someone was punching it. Then everything ju-", "hold": 3.6},
        {"wait": 1.8},
        {"caption": "What?", "hold": 1.4, "center": True},
        {"caption": "Where is…What's going on?", "hold": 1.8, "center": True},
        {"caption": "What's going on?", "hold": 1.4, "center": True},
        {"caption": "I'm dreaming right now.", "hold": 1.8, "center": True},
        {"caption": "Am I drea-", "hold": 0.6, "center": True},
        {"flash": "#e9dfc7", "time": 0.6},
        {"shake": 16},
        {"caption": "The oddly normal feeling of his right pinky being snapped in half brought his eyes wide open before the pain even registered.", "center": True},
        {"wound": "Right pinky, snapped in half (Coldharbour)"},
        {"hide": "grabber", "wait": False},
        {"teleport": "bearded", "to": [13, 4]},
        {"teleport": "wiry", "to": [10, 4]},
        {"show": "bloody", "wait": False},
        {"show": "tall_man", "wait": False},
        {"pose": "player", "art": "char/derrick_man_sit_field"},
        {"camera": [11.5, 3.2], "time": 0.0},
        {"zoom": 1.75, "time": 0.1},
        {"light": "lantern", "energy": 0.5, "time": 0.1},
        {"caption": "He screamed so suddenly he didn't have time to control it. Once it started, it didn't stop until they shoved the rag in his mouth. His eyes welled up in tears as he struggled to breathe.", "center": True},
        {"fade": "in", "time": 1.6},
        {"caption": "A tall, thin man stooped over in front of him."},
        {"act": "tall_man", "do": "raise"},
        {"talk": [["tall_man", "The Sons of St. Jack bless this city for this forage."]]},
        {"act": "tall_man", "do": "reset"},
        {"caption": "What?", "hold": 1.4},
        {"face": "bloody", "dir": "left"},
        {"act": "bloody", "do": "point"},
        {"talk": [["bloody", "Dead man!"]]},
        {"caption": "The man he headbutted stood to the tall man's right, pointing at him and demanding the right to cut his throat. He snarled, his left hand clutching a makeshift bandage to his mouth, soaked all the way through and dripping with blood."},
        {"act": "bloody", "do": "point"},
        {"talk": [["bloody", "He's a dead man!"]]},
        {"caption": "The tall man smiled.", "hold": 2.0},
        {"talk": [["tall_man", "I'd like to speak to him."]]},
        {"zoom": 1.25, "time": 2.4, "wait": False},
        {"light": "lantern", "energy": 1.1, "time": 2.4},
        {"caption": "The alleyway around him gradually came into focus. There must have been at least ten men, blades in hand. The man behind him pulled the rag out of his mouth and gave the back of his head a quick shove for good measure. The group made space around them."},
        {"zoom": 1.6, "time": 1.6, "wait": False},
        {"caption": "He looked up at the tall man and into his eyes."},
        {"caption": "What stared back at him was something warm.", "hold": 2.4},
        {"talk": [["tall_man", "What's your name, dead man?"]]},
        {"caption": "He felt his stomach drop.", "hold": 2.0},
        {"pose": "tall_man", "art": "char/jack_kneel_field"},
        {"zoom": 1.9, "time": 1.4, "wait": False},
        {"caption": "The tall man knelt down until they were face to face, looking him in the eye and smiling apologetically."},
        {"talk": [["tall_man", "What's your name, dead man?"], ["derrick", "…Derrick."],
                  ["tall_man", "Anyone to ransom you to Derrick? You don't much look it, but it's polite to ask."],
                  ["derrick", "…"]]},
        {"act": "player", "do": "shake"},
        {"caption": "He shook his head after thinking about it."},
        {"talk": [["tall_man", "Our bylaws technically demand I take your head for harming one our men. Of course, we still need to have a proper trial. Any chance you'll be a peach and plead guilty?"]]},
        {"caption": "Derrick didn't know what that meant, but felt he should maybe say no. Something in the tall man's eyes made him think he should."},
        {"prompt": ["", "Something else in them made him think it might not matter."], "choice": [
            {"text": "Shake your head.", "defiant": True, "then": [{"add": "defiance", "n": 1}]},
            {"text": "Nod.", "then": [{"add": "complicity", "n": 1}, {"caption": "He meant to nod. His head shook instead."}]}]},
        {"act": "player", "do": "shake"},
        {"caption": "He gave a short, quick shake of his head."},
        {"pose": "tall_man", "art": ""},
        {"zoom": 1.5, "time": 1.0, "wait": False},
        {"caption": "The Tall Man gave a strangely disappointed smile.", "hold": 2.4},
        {"talk": [["tall_man", "Bloody hate trials, I do. No justice in em."]]},
        {"face": "tall_man", "dir": "down"},
        {"caption": "The Tall Man turned around to face the men behind him.", "hold": 2.4},
        {"talk": [["tall_man", "Fetch the dogs."]]},
        {"fade": "out", "time": 0.12},
        {"set": "trial_by_dogs"},
        {"wait": 1.2},
        {"sound": "Dogs, somewhere close, starting to bark."},
        {"wait": 2.0},
        {"title_drop": "The Sons of St. Jack", "sub": "End of Act One"},
        {"end_act": True},
    ],
}
STAGES.append(s)

if __name__ == '__main__':
    for f in os.listdir(OUT):
        if f.endswith('.json'):
            os.remove(os.path.join(OUT, f))
    for st in STAGES:
        with open(os.path.join(OUT, st['id'] + '.json'), 'w') as fh:
            json.dump(st, fh, indent=1, ensure_ascii=False)
    print('wrote', len(STAGES), 'stages:', ', '.join(s['id'] for s in STAGES))
